version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
  mobile:
    build: ./mobile
    ports:
      - "8081:8081"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"